-- AlterTable
ALTER TABLE "ProductionOrder" ADD COLUMN "cpGoodQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProductionOrder" ADD COLUMN "cpNgQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ProductionOrder" ADD COLUMN "qcNgQty" INTEGER NOT NULL DEFAULT 0;